# =========================================================
# Alacritty Appearance - Rob Meijerink
# =========================================================

[window]
opacity = 0.8
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
dynamic_title = true

[font]
size = 10.0

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#000000"
foreground = "#eaeaea"

[colors.cursor]
background = "#f0f0f0"
foreground = "#26282a"
cursor = "#ECEFF4"
text = "#3B4252"

[colors.normal]
black   = "#26282a"
red     = "#ff8878"
green   = "#b4fb73"
yellow  = "#fffcb7"
blue    = "#8bbce5"
magenta = "#ffb2fe"
cyan    = "#a2e1f8"
white   = "#f1f1f1"

[colors.bright]
black   = "#6f6f6f"
red     = "#fe978b"
green   = "#d6fcba"
yellow  = "#fffed5"
blue    = "#c2e3ff"
cyan    = "#c0e9f8"
magenta = "#ffc6ff"
white   = "#ffffff"
