gui:
  showIcons: true
git:
  disableForcePushing: true
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  openCommand: 'nvim {{filename}}'
  editCommandTemplate: '{{editor}} +{{line}} -- {{filename}}'
  openCommand: 'nvim {{filename}}'
