#!/usr/bin/env bash
mkdir -p ~/.config/nvim/lua/robmeijerink
mkdir -p ~/.config/nvim/lua/robmeijerink/lsp
mkdir -p ~/.config/nvim/lua/robmeijerink/lsp/server-conf
mkdir -p ~/.config/nvim/lua/robmeijerink/debugger

mkdir -p ~/.config/nvim/after
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/after/plugin/keymap

mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

# Symlink all
for f in $(find nvim -regex ".*\.lua$"); do
	rm -rf ~/.config/nvim/$f
	ln -s $(pwd)/$f ~/.config/$f
done

# ln -s $(pwd)/i3/config ~/.config/i3/config
# ln -s $(pwd)/i3status/config ~/.config/i3status/config

echo "Installed!"
