#!/usr/bin/env bash
mkdir -p ~/.config/nvim/lua
mkdir -p ~/.config/nvim/lua/lsp
mkdir -p ~/.config/nvim/lua/lsp/server-conf

mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

# Symlink all
for f in `find . -regex ".*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s $(pwd)/$f ~/.config/nvim/$f
done

echo "Installed!"
