#!/usr/bin/env bash
mkdir -p ~/.config/nvim/lua/robmeijerink
mkdir -p ~/.config/nvim/lua/robmeijerink/lsp
mkdir -p ~/.config/nvim/lua/robmeijerink/lsp/server-conf

mkdir -p ~/.config/nvim/after
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/after/plugin/keymap

mkdir -p ~/.vim/tmp/undo
mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

# Symlink all
for f in `find . -regex ".*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s $(pwd)/$f ~/.config/nvim/$f
done

echo "Installed!"
